// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_C0bpNrefL36WhO7usIeCsb9TvjhdqrQ',
    appId: '1:292390004026:web:6f5f0ddaad2cc62faddc03',
    messagingSenderId: '292390004026',
    projectId: 'final-2025-v1',
    authDomain: 'final-2025-v1.firebaseapp.com',
    storageBucket: 'final-2025-v1.firebasestorage.app',
    measurementId: 'G-LBCMYX3G1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnR1OrBG4s0wn0Qi1kxmXXR0mxImsxhp8',
    appId: '1:292390004026:android:e9192d37b5910c22addc03',
    messagingSenderId: '292390004026',
    projectId: 'final-2025-v1',
    storageBucket: 'final-2025-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXkIRpWVH1rSrnq-eL5-9wwR88vcc33cE',
    appId: '1:292390004026:ios:2d8bff6d687c0082addc03',
    messagingSenderId: '292390004026',
    projectId: 'final-2025-v1',
    storageBucket: 'final-2025-v1.firebasestorage.app',
    iosBundleId: 'com.example.finalIug2025',
  );
}
